### PR TITLE
yath failed: do not die on zero failures

### PR DESCRIPTION
**Pull request by rjbs**

### CODE REVIEW

**Comment by exodist** [comment]
I would be very curious to see what you ran to make this necessary.

**Comment by rjbs** [comment]
I ran "yath failures" on a jsonl log with no failures in it.  That's all!

**Comment by rjbs** [comment]
To elaborate just a tiny bit:  I am writing a very small amount of automation that injects a program into a test VM, uses that program to run the test suite, and then I extract the jsonl file for analysis by the automation program, which then uploads a report to a shared workspace.

Part of that analysis is "see whether there are failures," which it does by running yath failures.  But that dies if there are none!

Even if the simplest thing is "use some other mechanism to determine that," it seems like dying on a zero-failure log is just sub-optimal behavior.

**Comment by exodist** [comment]
Thats what I get for looking at this on my phone, I thought this was for the test command, haha.

**Pull request merged**
